### ISSUE TITLE
pydantic.env_settings.SettingsError: error parsing env var "bot_credentials"

### ISSUE THREAD

**Issue by vtimer** [ExpressApp/async-box#147]
При запуске  alembic upgrade head пишет ошибку 
pydantic.env_settings.SettingsError: error parsing env var "bot_credentials"

в .env переменная BOT_CREDENTIALS указана

**Comment by kutuzov13** [comment]
BOT_CREDENTIALS cостоят из блоков `cts_host@secret_key@bot_id`, разделённых запятыми (один бот может быть
зарегистрирован на нескольких CTS). `cts_host` - адрес админки, `secret_key` и `bot_id` можно получить после регистрации бота, нажав на его имя.   
Инструкция по регистрации бота находится в [Руководствe администратора](https://express.ms/admin_guide.pdf) `->` Эксплуатация корпоративного сервера `->` Управление контактами `->` Чат-боты.
